import React from "react";
import PropTypes from "prop-types"; // Add this import
import { Open_Sans } from "next/font/google";
import { Raleway } from "next/font/google";
const openSans = Open_Sans({ subsets: ["latin"] ,weight: ['400', '600'],display: 'swap', variable: '--font-open-sans',});
const raleway = Raleway({ subsets: ["latin"], weight: ['400', '600'],display: 'swap', variable: '--font-raleway', });


import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

RootLayout.propTypes = {
  children: PropTypes.node.isRequired, // Add this prop type validation
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${raleway.variable}  lg:w-[85%] m-auto`}>
        <Navbar />
        {children}
        </body>
    </html>
  );
}
